apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMi5jZ2htdzhrZTJzeWYudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: bmF2ZWVuMTIzNA==
